# ROS 2 Galactic Geochelone development containers build specification.
#
# Roberto Masocco <robmasocco@gmail.com>
#
# April 23, 2022

version: '3.9'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: intelligentsystemslabutv/ros2env:dev

  nvidia:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    image: intelligentsystemslabutv/ros2env:nvidia
